FROM golang:alpine

RUN apk add --no-cache git make
RUN go get github.com/bluebreezecf/opentsdb-goclient
RUN go get github.com/graph-gophers/graphql-go
RUN go get github.com/functionalfoundry/graphqlws
